import { Injectable } from '@angular/core';
import { AreaAtuacao } from './area-atuacao';
import { Observable } from 'rxjs/Observable';
import { of } from 'rxjs/observable/of';

@Injectable()
export class AreaAtuacaoService {

  constructor() { }
  list: AreaAtuacao[] = [
    { descricao: 'Administração Comercial/Vendas' },
    { descricao: 'Administração de Empresas' },
    { descricao: 'Administração Pública' },
    { descricao: 'Advocacia/Jurídica' },
    { descricao: 'Agronomia' },
    { descricao: 'Arquitetura/Urbanismo' },
    { descricao: 'Artes Cênicas' },
    { descricao: 'Artes Gráficas' },
    { descricao: 'Artes Plásticas' },
    { descricao: 'Atend. a cliente - Bares/Restaurantes' },
    { descricao: 'Atend. a cliente - Telefonistas/Recepcionistas' },
    { descricao: 'Atend. a cliente - Telemarketing/Call Center' },
    { descricao: 'Atend. a cliente' },
    { descricao: 'Auditoria' },
    { descricao: 'Bancos' },
    { descricao: 'Biblioteconomia' },
    { descricao: 'Biologia/Ciências Biológicas' },
    { descricao: 'Biomedicina' },
    { descricao: 'Ciências Sociais' },
    { descricao: 'Cinema' },
    { descricao: 'Comércio Exterior' },
    { descricao: 'Compras' },
    { descricao: 'Comunicação' },
    { descricao: 'Construção Civil' },
    { descricao: 'Contabilidade' },
    { descricao: 'Controladoria' },
    { descricao: 'Culinária/Gastronomia' },
    { descricao: 'Desenho Industrial' },
    { descricao: 'Design de Interiores' },
    { descricao: 'Design Gráfico' },
    { descricao: 'Ecologia/Meio Ambiente' },
    { descricao: 'Economia' },
    { descricao: 'Enfermagem' },
    { descricao: 'Engenharia de Alimentos' },
    { descricao: 'Engenharia Civil' },
    { descricao: 'Engenharia Eletrônica' },
    { descricao: 'Engenharia Eletrotécnica' },
    { descricao: 'Engenharia Mecânica' },
    { descricao: 'Engenharia Metalúrgica e de Materias' },
    { descricao: 'Engenharia de Minas' },
    { descricao: 'Engenharia de Produção' },
    { descricao: 'Engenharia Química' },
    { descricao: 'Engenharia - Outras' },
    { descricao: 'Ensino Superior e Pesquisa' },
    { descricao: 'Ensino - Outros' },
    { descricao: 'Entretenimento' },
    { descricao: 'Esportes' },
    { descricao: 'Estética' },
    { descricao: 'Farmácia' },
    { descricao: 'Filosofia' },
    { descricao: 'Finanças' },
    { descricao: 'Fiscal' },
    { descricao: 'Física' },
    { descricao: 'Fisioterapia' },
    { descricao: 'Fonoaudiologia' },
    { descricao: 'Geografia' },
    { descricao: 'Geologia' },
    { descricao: 'Gestão Empresarial' },
    { descricao: 'História' },
    { descricao: 'Hotelaria' },
    { descricao: 'Informática/T.I.' },
    { descricao: 'Internet' },
    { descricao: 'Jornalismo' },
    { descricao: 'Letras' },
    { descricao: 'Logística' },
    { descricao: 'Manutenção Industrial' },
    { descricao: 'Manutenção Predial' },
    { descricao: 'Marketing' },
    { descricao: 'Matemática/Estatística' },
    { descricao: 'Medicina/Hospitalar' },
    { descricao: 'Meteorologia' },
    { descricao: 'Mineração' },
    { descricao: 'Moda' },
    { descricao: 'Museologia' },
    { descricao: 'Música' },
    { descricao: 'Nutrição' },
    { descricao: 'Oceanografia' },
    { descricao: 'Odontologia' },
    { descricao: 'Organização de Eventos/Produção Cultural' },
    { descricao: 'Organização e Métodos' },
    { descricao: 'Pesquisa de Mercado' },
    { descricao: 'Petrolífera' },
    { descricao: 'Produção/Fabricação' },
    { descricao: 'Propaganda' },
    { descricao: 'Psicologia' },
    { descricao: 'Qualidade' },
    { descricao: 'Química' },
    { descricao: 'Radialismo e Televisão' },
    { descricao: 'Recursos Humanos' },
    { descricao: 'Relações Internacionais' },
    { descricao: 'Relações Públicas' },
    { descricao: 'Secretariado' },
    { descricao: 'Segurança e Saúde no Trabalho' },
    { descricao: 'Segurança Patrimonial' },
    { descricao: 'Seguros' },
    { descricao: 'Serviço Social' },
    { descricao: 'Serviço Administrativo' },
    { descricao: 'Serviços Domésticos ' },
    { descricao: 'Serviços Gerais' },
    { descricao: 'Serviços Técnicos - Elétricos' },
    { descricao: 'Serviços Técnicos - Eletrônicos' },
    { descricao: 'Serviços Técnicos - Mecânicos' },
    { descricao: 'Serviços Técnicos - Outros' },
    { descricao: 'Suprimentos' },
    { descricao: 'Telecomunicações' },
    { descricao: 'Terapia Ocupacional' },
    { descricao: 'Terceiro Setor/Responsabilidade Social' },
    { descricao: 'Tradução/Interpretação' },
    { descricao: 'Transporte Aéreo' },
    { descricao: 'Transporte Marítimo' },
    { descricao: 'Transporte Terrestre' },
    { descricao: 'Tributária' },
    { descricao: 'Turismo' },
    { descricao: 'Vendas' },
    { descricao: 'Veterinária' },
    { descricao: 'Web Design' },
    { descricao: 'Zoologia' },
    { descricao: 'Zootecnia ' },
    { descricao: 'Outros.' }
  ];

  getAll(): Observable<AreaAtuacao[]> {
    return of(this.list);
  }
}
